FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV=production
ENV HUSKY=0

# Install deps
COPY package*.json ./
RUN npm ci --omit=dev --ignore-scripts && npm cache clean --force

# Copy build
COPY dist ./dist

# Security
RUN addgroup -S nodejs && adduser -S nodejs -G nodejs
USER nodejs

# Start worker
CMD ["node", "dist/workers/message.worker.js"]